model:
  cldm:
    target: diffbir.model.cldm.ControlLDM
    params:
      latent_scale_factor: 0.18215
      unet_cfg:
        use_checkpoint: True
        image_size: 32 # unused
        in_channels: 4
        out_channels: 4
        model_channels: 320
        attention_resolutions: [ 4, 2, 1 ]
        num_res_blocks: 2
        channel_mult: [ 1, 2, 4, 4 ]
        num_head_channels: 64 # need to fix for flash-attn
        use_spatial_transformer: True
        use_linear_in_transformer: True
        transformer_depth: 1
        context_dim: 1024
        legacy: False
      vae_cfg:
        embed_dim: 4
        ddconfig:
          double_z: true
          z_channels: 4
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
      clip_cfg:
        embed_dim: 1024
        vision_cfg:
          image_size: 224
          layers: 32
          width: 1280
          head_width: 80
          patch_size: 14
        text_cfg:
          context_length: 77
          vocab_size: 49408
          width: 1024
          heads: 16
          layers: 24
        layer: "penultimate"
      controlnet_cfg:
        use_checkpoint: True
        image_size: 32 # unused
        in_channels: 4
        hint_channels: 4
        model_channels: 320
        attention_resolutions: [ 4, 2, 1 ]
        num_res_blocks: 2
        channel_mult: [ 1, 2, 4, 4 ]
        num_head_channels: 64 # need to fix for flash-attn
        use_spatial_transformer: True
        use_linear_in_transformer: True
        transformer_depth: 1
        context_dim: 1024
        legacy: False

  swinir:
    target: diffbir.model.swinir.SwinIR
    params:
      img_size: 64
      patch_size: 1
      in_chans: 3
      embed_dim: 180
      depths: [6, 6, 6, 6, 6, 6, 6, 6]
      num_heads: [6, 6, 6, 6, 6, 6, 6, 6]
      window_size: 8
      mlp_ratio: 2
      sf: 8
      img_range: 1.0
      upsampler: "nearest+conv"
      resi_connection: "1conv"
      unshuffle: True
      unshuffle_scale: 8

  diffusion:
    target: diffbir.model.gaussian_diffusion.Diffusion
    params:
      linear_start: 0.00085
      linear_end: 0.0120
      timesteps: 1000
      zero_snr: False
      parameterization: eps

dataset:
  train:
    target: diffbir.dataset.codeformer_rgb_ocrRecLoss.CodeformerDataset
    params:
      # training file list path
      file_list: ./generated_data
      file_backend_cfg:
        target: diffbir.dataset.file_backend.HardDiskBackend
      out_size: 448
      crop_type: center
      blur_kernel_size: 41
      kernel_list: ['iso', 'aniso']
      kernel_prob: [0.5, 0.5]
      blur_sigma: [0.1, 12]
      downsample_range: [1, 12]
      noise_range: [0, 15]
      jpeg_range: [30, 100]
  val:
    target: diffbir.dataset.codeformer_rgb_ocrRecLoss.CodeformerDataset
    params:
      # training file list path
      file_list: ./generated_data
      file_backend_cfg:
        target: diffbir.dataset.file_backend.HardDiskBackend
      out_size: 448
      crop_type: center
      blur_kernel_size: 41
      kernel_list: ['iso', 'aniso']
      kernel_prob: [0.5, 0.5]
      blur_sigma: [0.1, 12]
      downsample_range: [1, 12]
      noise_range: [0, 15]
      jpeg_range: [30, 100]
      mode: val
batch_transform:
  target: diffbir.dataset.batch_transform.IdentityBatchTransform

train:
  # pretrained sd v2.1 path
  sd_path: ./pretrained_weights/v2-1_512-ema-pruned.ckpt
  # stage 1 swinir path.
  # In our paper, we use SwinIR trained on ImageNet-1k with codeformer degradation.
  swinir_path: ./pretrained_weights/codeformer_swinir.ckpt
  # experiment directory path
  exp_dir: ./exp/server5
  # ImageNet 1k (1.3M images)
  # batch size = 192, lr = 1e-4, total training steps = 25k
  # Our filtered laion2b-en (15M images)
  # batch size = 256, lr = 1e-4 (first 30k), 1e-5 (next 50k), total training steps = 80k
  noise_aug_timestep: 0
  ckpt_every: 800
  save_unet: 800
  resume: ./pretrained_weights/DiffBIR_v2.1.pt
  num_workers: 4
  log_train_every: 10
  log_train_img_every: 25
  
val:
  val_batch_size: 6
  log_val_num_img: 6
  log_val_every: 100
  log_val_img_every: 100

train_settings:
  train_batch_size: 1
  learning_rate: 5e-6
  train_steps: 4000

wandb_args:
  wandb_key: e32eed0c2509bf898b850b0065ab62345005fb73
  wandb_exp_name: server5_gpu0_DiffBiR_FTctrlnet_bs1_lr5e-6_ocrRecLossOnlyWeight0.001

pho_args:
  ocr_loss_weight: 0.001
  fine_tuning_method: only_ctrlnet_fine_tuning

